language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libgtkmm-3.0-dev

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-4.9-dev
            - libgtkmm-3.0-dev

    - os: osx
      compiler: clang

before_install:
  # (Ignore brew error for possibly already installed package pkg-config.)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && { brew install pkg-config || true; brew install gtkmm3; }; fi

before_script:
  # Give information whether clang found a GCC 4.9 installation.
  - $CXX -v || true

script: make

notifications:
  irc: "chat.freenode.net#canvon"
